version: 1.0.{build}
configuration:
- Debug
- Release
platform: Any CPU
before_build:
- ps: dotnet restore
build_script:
- ps: dotnet build -c $env:CONFIGURATION
test_script:
- ps: dotnet test .\test\GuessNumberTest\GuessNumberTest.csproj
